// Generated by gencpp from file polhemus_ros_driver/calibrateRequest.msg
// DO NOT EDIT!


#ifndef POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATEREQUEST_H
#define POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace polhemus_ros_driver
{
template <class ContainerAllocator>
struct calibrateRequest_
{
  typedef calibrateRequest_<ContainerAllocator> Type;

  calibrateRequest_()
    {
    }
  calibrateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calibrateRequest_

typedef ::polhemus_ros_driver::calibrateRequest_<std::allocator<void> > calibrateRequest;

typedef boost::shared_ptr< ::polhemus_ros_driver::calibrateRequest > calibrateRequestPtr;
typedef boost::shared_ptr< ::polhemus_ros_driver::calibrateRequest const> calibrateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace polhemus_ros_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "polhemus_ros_driver/calibrateRequest";
  }

  static const char* value(const ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::polhemus_ros_driver::calibrateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATEREQUEST_H
