// Generated by gencpp from file polhemus_ros_driver/calibrate.msg
// DO NOT EDIT!


#ifndef POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATE_H
#define POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATE_H

#include <ros/service_traits.h>


#include <polhemus_ros_driver/calibrateRequest.h>
#include <polhemus_ros_driver/calibrateResponse.h>


namespace polhemus_ros_driver
{

struct calibrate
{

typedef calibrateRequest Request;
typedef calibrateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calibrate
} // namespace polhemus_ros_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::polhemus_ros_driver::calibrate > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::polhemus_ros_driver::calibrate&) { return value(); }
};

template<>
struct DataType< ::polhemus_ros_driver::calibrate > {
  static const char* value()
  {
    return "polhemus_ros_driver/calibrate";
  }

  static const char* value(const ::polhemus_ros_driver::calibrate&) { return value(); }
};


// service_traits::MD5Sum< ::polhemus_ros_driver::calibrateRequest> should match
// service_traits::MD5Sum< ::polhemus_ros_driver::calibrate >
template<>
struct MD5Sum< ::polhemus_ros_driver::calibrateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::polhemus_ros_driver::calibrate >::value();
  }
  static const char* value(const ::polhemus_ros_driver::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::polhemus_ros_driver::calibrateRequest> should match
// service_traits::DataType< ::polhemus_ros_driver::calibrate >
template<>
struct DataType< ::polhemus_ros_driver::calibrateRequest>
{
  static const char* value()
  {
    return DataType< ::polhemus_ros_driver::calibrate >::value();
  }
  static const char* value(const ::polhemus_ros_driver::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::polhemus_ros_driver::calibrateResponse> should match
// service_traits::MD5Sum< ::polhemus_ros_driver::calibrate >
template<>
struct MD5Sum< ::polhemus_ros_driver::calibrateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::polhemus_ros_driver::calibrate >::value();
  }
  static const char* value(const ::polhemus_ros_driver::calibrateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::polhemus_ros_driver::calibrateResponse> should match
// service_traits::DataType< ::polhemus_ros_driver::calibrate >
template<>
struct DataType< ::polhemus_ros_driver::calibrateResponse>
{
  static const char* value()
  {
    return DataType< ::polhemus_ros_driver::calibrate >::value();
  }
  static const char* value(const ::polhemus_ros_driver::calibrateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POLHEMUS_ROS_DRIVER_MESSAGE_CALIBRATE_H
