// Generated by gencpp from file polhemus_ros_driver/set_source.msg
// DO NOT EDIT!


#ifndef POLHEMUS_ROS_DRIVER_MESSAGE_SET_SOURCE_H
#define POLHEMUS_ROS_DRIVER_MESSAGE_SET_SOURCE_H

#include <ros/service_traits.h>


#include <polhemus_ros_driver/set_sourceRequest.h>
#include <polhemus_ros_driver/set_sourceResponse.h>


namespace polhemus_ros_driver
{

struct set_source
{

typedef set_sourceRequest Request;
typedef set_sourceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_source
} // namespace polhemus_ros_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::polhemus_ros_driver::set_source > {
  static const char* value()
  {
    return "a11e7ea3e225df8a203dc448504ef4dd";
  }

  static const char* value(const ::polhemus_ros_driver::set_source&) { return value(); }
};

template<>
struct DataType< ::polhemus_ros_driver::set_source > {
  static const char* value()
  {
    return "polhemus_ros_driver/set_source";
  }

  static const char* value(const ::polhemus_ros_driver::set_source&) { return value(); }
};


// service_traits::MD5Sum< ::polhemus_ros_driver::set_sourceRequest> should match
// service_traits::MD5Sum< ::polhemus_ros_driver::set_source >
template<>
struct MD5Sum< ::polhemus_ros_driver::set_sourceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::polhemus_ros_driver::set_source >::value();
  }
  static const char* value(const ::polhemus_ros_driver::set_sourceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::polhemus_ros_driver::set_sourceRequest> should match
// service_traits::DataType< ::polhemus_ros_driver::set_source >
template<>
struct DataType< ::polhemus_ros_driver::set_sourceRequest>
{
  static const char* value()
  {
    return DataType< ::polhemus_ros_driver::set_source >::value();
  }
  static const char* value(const ::polhemus_ros_driver::set_sourceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::polhemus_ros_driver::set_sourceResponse> should match
// service_traits::MD5Sum< ::polhemus_ros_driver::set_source >
template<>
struct MD5Sum< ::polhemus_ros_driver::set_sourceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::polhemus_ros_driver::set_source >::value();
  }
  static const char* value(const ::polhemus_ros_driver::set_sourceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::polhemus_ros_driver::set_sourceResponse> should match
// service_traits::DataType< ::polhemus_ros_driver::set_source >
template<>
struct DataType< ::polhemus_ros_driver::set_sourceResponse>
{
  static const char* value()
  {
    return DataType< ::polhemus_ros_driver::set_source >::value();
  }
  static const char* value(const ::polhemus_ros_driver::set_sourceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POLHEMUS_ROS_DRIVER_MESSAGE_SET_SOURCE_H
