(cl:defpackage polhemus_ros_driver-srv
  (:use )
  (:export
   "CALIBRATE"
   "<CALIBRATE-REQUEST>"
   "CALIBRATE-REQUEST"
   "<CALIBRATE-RESPONSE>"
   "CALIBRATE-RESPONSE"
   "PERSIST"
   "<PERSIST-REQUEST>"
   "PERSIST-REQUEST"
   "<PERSIST-RESPONSE>"
   "PERSIST-RESPONSE"
   "SET_SOURCE"
   "<SET_SOURCE-REQUEST>"
   "SET_SOURCE-REQUEST"
   "<SET_SOURCE-RESPONSE>"
   "SET_SOURCE-RESPONSE"
  ))

